name       : atom
version    : 1.9.4
release    : 49
source     :
    - https://github.com/atom/atom/archive/v1.9.4.tar.gz : 3cef23b12b874b999283cd1f4d533af84a3035e12c524048c580972783bfd8a1
license    : MIT
component  : editor
summary    : Atom is a hackable text editor for the 21st century.
description: |
    Atom is a hackable text editor for the 21st century.
ccache     : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps    :
    - gconf
    - git
    - nodejs
build      : |
    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build
    install -Dm644 $pkgfiles/atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
