name       : atom
version    : 1.12.9
release    : 65
source     :
    - https://github.com/atom/atom/archive/v1.12.9.tar.gz : 2616bab176f8be6ba1ca7997c84e62490b0e093d2d03982b9934cfeedb590e8f
license    : MIT
component  : programming.ide
summary    : Atom is a hackable text editor for the 21st century.
description: |
    Atom is a hackable text editor for the 21st century.
ccache     : no
networking : yes
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(xkbfile)
    - git
    - nodejs-devel
rundeps    :
    - gconf
    - git
    - nodejs
build      : |
    mkdir -p %installroot%/usr/bin/
    script/build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/share/atom/
    find out/atom-$version-amd64 \
        -path "*/apm/etc" -prune -exec rm -r '{}' \; \
        -or -path "*/git-utils/deps" -prune -exec rm -r '{}' \; \
        -or -path "*/git-utils/src" -prune -exec rm -r '{}' \; \
        -or -path "*/keytar/src" -prune -exec rm -r '{}' \; \
        -or -path "*/oniguruma/deps" -prune -exec rm -r '{}' \; \
        -or -path "*/oniguruma/src" -prune -exec rm -r '{}' \; \
        -or -path "*.md" -prune -exec rm -r '{}' \; \
        -or -name "LICENSE" -prune -exec rm -r '{}' \; \
        -or -name "doc" -prune -exec rm -r '{}' \; \
        -or -name "example" -prune -exec rm -r '{}' \; \
        -or -name "examples" -prune -exec rm -r '{}' \; \
        -or -name "license" -prune -exec rm -r '{}' \; \
        -or -name "man" -prune -exec rm -r '{}' \; \
        -or -name "obj.target" -prune -exec rm -r '{}' \; \
        -or -name "samples" -prune -exec rm -r '{}' \; \
        -or -name "test" -prune -exec rm -r '{}' \; \
        -or -name "tests" -prune -exec rm -r '{}' \; \
        -or -name "tst" -prune -exec rm -r '{}' \;
    cp -R out/atom-$version-amd64/* $installdir/usr/share/atom/
    ln -s /usr/share/atom/resources/app/apm/bin/apm $installdir/usr/bin/apm
    ln -s /usr/share/atom/atom $installdir/usr/bin/atom
    install -Dm644 $pkgfiles/atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
