name       : atom
version    : 1.10.1
release    : 55
source     :
    - https://github.com/atom/atom/archive/v1.10.1.tar.gz : 0cee5d9f32c437a21018f3f8efe57f1e855f059c83c158643c1f2bd311e6b8a5
license    : MIT
component  : programming.ide
summary    : Atom is a hackable text editor for the 21st century.
description: |
    Atom is a hackable text editor for the 21st century.
ccache     : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps    :
    - gconf
    - git
    - nodejs
build      : |
    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build
    install -Dm644 $pkgfiles/atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
