name       : atom
version    : 1.2.3
release    : 24
source     :
    - https://github.com/atom/atom/archive/v1.2.3.tar.gz : 33483c28ce56a08b70c7bea326ae55f19eaa0922bab971e8c30ccafeede9550c
license    : MIT
summary    : Atom is a hackable text editor for the 21st century.
description: |
   Atom is a hackable text editor for the 21st century.
ccache : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps :
    - gconf
    - git
    - nodejs
build      : |
    export DESCRIPTION="Atom is a hackable text editor for the 21st century."

    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build

    sed -e "s/<%= description %>/$DESCRIPTION/"  \
        -e "s|<%= appName %>|Atom|"\
        -e "s|<%= installDir %>/share/<%= appFileName %>|/usr/bin|"\
        -e "s|<%= iconPath %>|atom|"\
        resources/linux/atom.desktop.in > resources/linux/Atom.desktop

    install -Dm644 resources/linux/Atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
