name       : atom
version    : 1.0.7
release    : 16
source     :
    - https://github.com/atom/atom/archive/v1.0.7.tar.gz : e7efb2df89379fe7f5092bdd40675c1f402fb80c7894b8c0d926e0690bfe4677
license    : MIT
summary    : Atom is a hackable text editor for the 21st century.
description: |
   Atom is a hackable text editor for the 21st century.
ccache : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps :
    - gconf
    - git
    - nodejs
build      : |
    export DESCRIPTION="Atom is a hackable text editor for the 21st century."

    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build

    sed -e "s/<%= description %>/$DESCRIPTION/"  -e "s|<%= executable %>|/usr/bin/atom|"  -e "s|<%= iconName %>|atom|" resources/linux/atom.desktop.in > resources/linux/Atom.desktop

    install -Dm644 resources/linux/Atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/atom.png %installroot%/usr/share/pixmaps/atom.png
