name       : atom
version    : 1.7.1
release    : 41
source     :
    - https://github.com/atom/atom/archive/v1.7.1.tar.gz : 101e4676542fff7712ad5cd58876f7377747c3ed8dfdb46adb013c695d5171a4
license    : MIT
summary    : Atom is a hackable text editor for the 21st century.
description: |
   Atom is a hackable text editor for the 21st century.
ccache : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps :
    - gconf
    - git
    - nodejs
build      : |
    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build
    install -Dm644 $pkgfiles/atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
