name       : atom
version    : 1.9.6
release    : 50
source     :
    - https://github.com/atom/atom/archive/v1.9.6.tar.gz : 4c27d2344e28d4156eff8a88ed0b66884a77f7e4b2cbaf316c6451b24fd7ff97
license    : MIT
component  : editor
summary    : Atom is a hackable text editor for the 21st century.
description: |
    Atom is a hackable text editor for the 21st century.
ccache     : no
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - git
    - nodejs-devel
rundeps    :
    - gconf
    - git
    - nodejs
build      : |
    mkdir -p %installroot%/usr/bin/
    script/build --build-dir %installroot%/atom-build
    script/grunt install --build-dir %installroot%/atom-build --install-dir %installroot%/usr
    rm -rf %installroot%/atom-build
    install -Dm644 $pkgfiles/atom.desktop %installroot%/usr/share/applications/atom.desktop
    install -Dm644 resources/app-icons/stable/png/512.png %installroot%/usr/share/pixmaps/atom.png
